export const metadata = {
  title: 'Terms of Service - FitMixs',
  description: 'Terms of Service for FitMixs AI Virtual Try-On.',
};

export default function TermsOfService() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-12 prose prose-blue">
      <h1>Terms of Service</h1>
      <p>Last updated: {new Date().toLocaleDateString()}</p>
      
      <h2>1. Use of service</h2>
      <p>By using FitMixs, you agree to these terms. You must not use the service for any illegal or unauthorized purpose.</p>

      <h2>2. User content</h2>
      <p>You retain all rights to the images you upload. You grant us a temporary license to process these images solely for the purpose of providing the AI virtual try-on service to you.</p>

      <h2>3. AI generated images</h2>
      <p>The outfits and images generated by FitMixs are created using artificial intelligence. We do not guarantee perfect accuracy in rendering.</p>

      <h2>4. Liability</h2>
      <p>FitMixs is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the service.</p>

      <h2>5. Termination</h2>
      <p>We may terminate or suspend your access to our service immediately, without prior notice or liability, for any reason whatsoever.</p>
    </div>
  );
}
